CMakeLists.txt

CMakeLists.txt: CMAKE_CXX_FLAGS Ninja bug fix

---

CMakeLists.txt

main.cpp: qt5-virtualkeyboard activated

CMakeLists.txt: bin name changed from VfDecGui to vf-declarative-gui

---

CMakeLists.txt

The superbuild project will not work otherwise.

CMakeLists.txt: moved QT dep QML from behind REQUIRED to the other deps.

---

appdata.qrc
qml/controls/settings/ApplicationSettings.qml
qml/controls/settings/DeviceSettings.qml
qml/controls/settings/Settings.qml

Added Application, Device, Ethernet and Wifi tab.
It is mandantory to have networksettings installed to run this application.
Please note that QML2_IMPORT_PATH must be set.

Adapted Settings Page

---

appdata.qrc
qml/controls/settings/ApplicationSettings.qml
qml/controls/settings/DeviceSettings.qml
qml/controls/settings/Settings.qml

Added Application and Device Tab
This should be only the existing Tab Settings commit.
I will care about the text colour later because there are not many days left this month.
Surprisingly, it seems that I'm on vacation next week.

Restructured settings from on page to tabs

---

qml/controls/error_comparison_params/ParamViewComparison.qml
qml/controls/error_comparison_params/ParamViewRegister.qml
qml/controls/range_module/RangePeak.qml
qml/controls/settings/ApplicationSettings.qml
qml/controls/settings/Settings.qml

Application settings follow-up + cleanups

---

.gitmodules
3rdparty/include3rdParty.cmake
CMakeLists.txt
qml/controls/settings/Settings.qml

under settings -> NETWORK SETTINGS (TAB)
It was necessary to remove SortFilterProxyModel code before. Functions were defined twice.

Added Networkmanager to vf-declarative-gui

---

qml/controls/settings/Settings.qml
src/zeratranslation.cpp

Make network-settings tab text translatable

---

.gitmodules

Remove leftover submodule

---

CMakeLists.txt

1. Please first review JsonSettingsQml pull request.
2. tell me
3. I will add submodule to vf metaproject and send a pull request
4. Review vf-metaproject pull request
5. Review vf-qmllibs pull request
6. Then finally review this pull request

CMakeLists.txt : linking project against JsonSettingsQml

---

CMakeLists.txt
appdata.qrc
qml/controls/MainToolBar.qml
qml/controls/PageView.qml
qml/controls/customerdata/CustomerDataBrowser.qml
qml/controls/customerdata/CustomerDataEditor.qml
qml/controls/customerdata/CustomerDataEntry.qml
qml/controls/error_comparison_common/ErrorMarginView.qml
qml/controls/error_comparison_common/MeasurementView.qml
qml/controls/error_comparison_params/ParamViewComparison.qml
qml/controls/error_comparison_params/ParamViewRegister.qml
qml/controls/harmonic_power_module/HarmonicPowerCharts.qml
qml/controls/logger/LoggerDbLocationSelector.qml
qml/controls/settings/ApplicationSettings.qml
qml/controls/settings/DeviceSettings.qml
qml/controls/settings/FrequencyInOutConfigPopup.qml
qml/controls/settings/Settings.qml
qml/controls/settings/SettingsInterval.qml
qml/main.qml
qml/pages/BurdenModulePage.qml
qml/pages/CEDModulePage.qml
qml/pages/ErrorCalculatorModulePage.qml
qml/pages/ErrorRegisterModulePage.qml
qml/pages/OsciModulePage.qml
qml/pages/PowerModulePage.qml
qml/pages/TransformerModulePage.qml
qml/singletons/GlobalConfig.qml
src/main.cpp

These belong to thos just sent to vf-qmllibs

Further refactor

---

qml/controls/error_comparison_params/ParamViewComparison.qml
qml/controls/error_comparison_params/ParamViewRegister.qml
qml/singletons/GlobalConfig.qml

Follow-up on vf-qmllibs: remove standardMargin

---

appdata.qrc
qml/controls/MainToolBar.qml
qml/controls/logger/LoggerDatasetSelector.qml
qml/controls/logger/LoggerDbLocationSelector.qml
qml/controls/logger/LoggerDbSearchDialog.qml
qml/controls/logger/LoggerMenu.qml
qml/controls/logger/LoggerRecordNamePopup.qml
qml/controls/logger/LoggerSettings.qml
qml/main.qml

Please take your time and test it and let me know what you think

Rework logging related gui

---

qml/controls/logger/LoggerMenu.qml
qml/controls/logger/LoggerRecordNameSelector.qml
qml/pages/CEDModulePage.qml
qml/pages/RefModulePage.qml

* Pimp Logger record name selector
* Let COM5003 specific pages update context properly
* Set context & transaction before start of logger

Logger record selector

---

qml/controls/logger/LoggerDbLocationSelector.qml
qml/controls/logger/LoggerSettings.qml

It does not make sense to allow changing database while a recording is running

Logger: Add plausis in settings / comments

---

appdata.qrc
qml/controls/MainToolBar.qml
qml/controls/customerdata/CustomerDataBrowser.qml
qml/controls/logger/LoggerDataContextOverview.qml
qml/controls/logger/LoggerMenu.qml
qml/controls/logger/LoggerRecordNameSelector.qml
qml/controls/logger/LoggerSettingsStack.qml
qml/pages/ActualValueTabsPage.qml
qml/pages/BurdenModulePage.qml
qml/pages/CEDModulePage.qml
qml/pages/ComparisonTabsView.qml
qml/pages/FftTabPage.qml
qml/pages/HarmonicPowerTabPage.qml
qml/pages/RefModulePage.qml
qml/pages/TransformerModulePage.qml
qml/singletons/GlobalConfig.qml

This is the initial work to link gui-contexts to db-contexts (running on my MT currently)

Logger gui

---

qml/controls/logger/LoggerExport.qml

LoggerExport: Set new parameters for decimals / locale at MTVis export

---

qml/pages/ComparisonTabsView.qml
qml/pages/ErrorRegisterModulePage.qml

Display actual power for power comparison measurement

---

qml/controls/logger/LoggerCustomDataSelector.qml
qml/controls/logger/LoggerMenu.qml
qml/singletons/GlobalConfig.qml

One of the results of watching Arthur working on the machine - and it was not his error

Custom data fix

---

qml/controls/harmonic_power_module/HarmonicPowerCharts.qml

* Fix pinch after snap rework
* Make flickable direction explicit
* Fix overshoot

HarmonicPowerCharts: After snap / overshoot fixes

---

qml/controls/error_comparison_common/MeasurementView.qml
qml/controls/error_comparison_params/ParamViewComparison.qml
qml/controls/error_comparison_params/ParamViewRegister.qml

Error comparison views: Remove unneeded QwtChart import

---

qml/controls/range_module/RangeMenu.qml

Please node this is the first try to push "dead WIP" code into master. We can not tell the consequences yet.

Wip ext transformer

---

qml/controls/fft_module/FftTable.qml
qml/controls/logger/LoggerExport.qml

* 2 patches taken from https://github.com/ZeraGmbH/vf-declarative-gui/pull/157
* 3rd patch replaces by string shortening

This and that

---

qml/controls/logger/LoggerCustomDataSelector.qml

This helper has already been implemented long time ago but got lost by making
all radios dynamic.

LoggerCustomDataSelector: Make custom content default when changed

---

.github/workflows/buildAndTest.yml
.github/workflows/triggerMetaUpdates.yml

Adding CI to vf-dec-gui
This will be the first upstream repo attempt

Add build and zera-metaproject upgrade CI

---

.github/workflows/triggerMetaUpdates.yml

Fix yml syntax error on triggerMetaUpdates.yml

---

.github/workflows/buildAndTest.yml
.github/workflows/triggerMetaUpdates.yml

Use newest CI files

---

appdata.qrc
qml/pages/SourceModulePage.qml
qml/pages/SourceModuleTabPage.qml

Add an initial source page

---

qml/pages/BurdenModulePage.qml

The current burden does not need a range factor.

Remove current burden range factor

---

qml/controls/settings/SerialSettings.qml

SerialSettings: Fix some warning on Qt 5.15

---

qml/pages/SourceModulePage.qml

SourceModulePage: Draw phase 2&3 darker when symmetric is active

---

qml/controls/PageView.qml

For now mark them as experimental

PageView.qml: Add initial support for DC-Sessions

---

qml/Main.qml

Hide rotary field indicator on dc-sessions

---

qml/pages/ActualValueTabsPage.qml

ActualValueTabsPage: Do not show vectors in DC sessions

---

appdata.qrc
qml/Main.qml
qml/controls/error_comparison_params/ParamViewComparison.qml
qml/controls/error_comparison_params/ParamViewRegister.qml
qml/pages/ActualValueTabsPage.qml
qml/pages/DCActualValueTabsPage.qml

We remove DC hacks from ActualValueTabsPage

Introduce a new tab for DC actual values

---

qml/singletons/GlobalConfig.qml

Set Vector views' default for circle to maximum value

---

qml/controls/PageView.qml

Find an initial displaye name for LEM-DC session

---

CMakeLists.txt

Signed-off-by: Anuja Mutalik <a.mutalik@zera.de>

Enable cross-compiling for tests

---

qml/controls/MainToolBar.qml

Signed-off-by: Asmae Kaouissi <a.kaouissi@zera.de>

MainToolBar: Change to window selection overview unconditionally

---

qml/controls/harmonic_power_module/HarmonicPowerTable.qml

HarmonicPowerTable: Translate relative (%) units properly

---

qml/controls/settings/DeviceSettings.qml
qml/controls/settings/SettingsInterval.qml

Simplify code by letting SettingsInterval take care of its height itself

---

src/itemmodels/actualvalueemobacmodel.cpp

ActualValueEmobAcModel: Remove unneeded AUX/SUM definitions

---

qml/controls/MainToolBar.qml
qml/singletons/GlobalConfig.qml

Signed-off-by: Anuja Mutalik <a.mutalik@zera.de>

GlobalConfig: Introduce schnubbel detection

---

qml/controls/MainToolBar.qml

Hi A-Team (@asmae-ka  / @amutalik )
What are your thoughts?
If you agree: Just apply this one
If not: Let's talk

Revamp info button

---

qml/controls/settings/SettingsInterval.qml

* Interval units are changed from "sec" to "s"

SettingsInterval: Follow unit change from zera-classes

---

app/qml/pages/ErrorCalculatorModulePage.qml
app/qml/pages/ErrorRegisterModulePage.qml
app/qml/pages/QuartzModulePage.qml

* Multiplication is better readable
* Interesting: Start/Stop are not abbreviated on dynamic size changes

Error calculator pages: Rework pointSize calculation

---

app/qml/controls/error_comparison_common/MultipleErrorView.qml
app/qml/singletons/FunctionTools.qml

This reverts commit 3729685cd3bf1df6499e6fecbc6d2dfa0792c57f.

Revert "Remove removeDecimalGroupSeparators functions"

---

app/qml/singletons/FunctionTools.qml

We affect error calculator results
This reverts commit 6f5f131681a9ae488ef514be8a5aa4bec86be0d7.

Revert "FunctionTools.qml: Remove removeDecimalGroupSeparators function"

---

CMakeLists.txt

It caused unforeseeable results in zera-classes
This reverts commit 0a4d051ee23c5d3806fb4c68e2820be6b8893be7.

Revert "CMake: Increase min version"

---

app/qml/controls/appinfo/StatusView.qml
app/qml/controls/settings/Settings.qml
app/qml/pages/ActualValueTabsPage.qml
app/qml/pages/BaseTabPage.qml
app/qml/pages/BurdenModulePage.qml
app/qml/pages/ComparisonTabsView.qml
app/qml/pages/DCActualValueTabsPage.qml
app/qml/pages/EMOBActualValueTabsPage.qml
app/qml/pages/FftTabPage.qml
app/qml/pages/HarmonicPowerTabPage.qml
app/qml/pages/SourceModuleTabPage.qml

@asmae-ka: That was the common place I had in mind.

Tabs: Try one fits all

---

app/main.cpp

On touch hovering highlighting is just annoying

main.cpp: Enable hover-highlighting on WebGL only

---

app/qml/controls/settings/DeviceSettings.qml

This reverts commit f24c879cc66d7a050f1ff13075ffa61de9504e5a.

Revert "DeviceSettings: hide rms cheating spinBox for non-dev users"

---

app/main.cpp

* They served their job: It is segfault killing the app
* After reading more: The implementation is horribly wrong and can cause many issues e.g shutdown problems

main.cpp: Remove signal handlers
