ZeraGmbH/vf-declarative-gui

qml/main.qml
qml/singletons/GlobalConfig.qml
src/main.cpp

Shelve the initial idea to control visibility of virtual keyboard by
environment variable 'QT_IM_MODULE' because in case variable is not set
application won't start complaining
| qrc:/qml/main.qml:385 Type InputPanel unavailable
| qrc:/QtQuick/VirtualKeyboard/content/InputPanel.qml:125 Type Keyboard unavailable
| qrc:/QtQuick/VirtualKeyboard/content/components/Keyboard.qml:36 module "QtQuick.VirtualKeyboard.Plugins" is not installed
For now this setting does not have a GUI backend because
* settings are subject of massive rework anyway
* we might introduce a magic for default value later
Fixes [1]
[1] https://github.com/ZeraGmbH/vf-declarative-gui/issues/41

Make virtual keyboard a persistant configuration

---

qml/controls/appinfo/StatusView.qml

Now we have from left to right:
* Device info
* Licenses info
* Device log
Side-effect: We do not open Device log by default: That has been un-usable
from the beginning and meanwhile it is completely broken by some change in
systemd.

StatusView: reorder tabs

---

CMakeLists.txt

Libs with Q_COREAPP_STARTUP_FUNCTION must be linked with --no-as-needed.
To achive that we deactivate --as-needed in front and reactivate it after linking
those libs. The rest can be build with global --as-needed

Enforced --no-as-needed for qml libs.

---

qml/controls/error_comparison_params/ParamViewComparison.qml

There is no validCCMP in the whole project and bug came in with
commit 1ba98eb07e0f189095517337ab79faf1d8ffcba2
Author: bhamacher <b.hamacher@zera.de>
Date:   Wed Jul 22 14:21:05 2020 +0200
Moved code to vf-qmllibs.
Following libs are replacing some parts of the code now:
zeraHelpers
zeraGlobalConfig
zeraComponents
zeraTranslation
zeraVeinComponents

ParamViewComparison.qml: Undo accidental change

---

qml/controls/logger/LoggerRecordNameSelector.qml
qml/controls/logger/LoggerSettings.qml
qml/controls/logger/LoggerSettingsStack.qml

* It is ugly
* It stopped working with changes in vf-logger (empty component array => all
components)
* As long as there is no support for customer content sets there is no need for
a view like this

LoggerSettings: remove view to select recorded values

---

qml/controls/logger/LoggerMenu.qml
qml/singletons/GlobalConfig.qml

This is not only a code prettification but we can now remove 'Custom Data'
menu for specific contexts.
The first example where we do so is COM5003's DC-Reference context:
It does not make sense to offer anything else but DC related contents.

LoggerMenu: Add 'Custom Data' menu to menus created dynamically

---

qml/controls/logger/LoggerExport.qml
qml/controls/logger/LoggerSettingsStack.qml

The view consists of three lines to control export:
1. Export type combo: We export MTVis and whole-database-copy currently
2. Target drive combo: Select mounted drive - visible only in case more than
one external partitions are available (multiple sticks / stick with multiple
partitions)
3. Export name field: MTVis: writable (path to store XML to) / DB: readonly
(name of db-file)
Note that entities of vf-export are written as soon as values change. This is a
bit of a lazy solution assuming the time between user enters changes and
press 'export' is long enough for vein to apply values.

LoggerExport: Add necessary controls and functionality to prepare export

---

qml/controls/logger/LoggerMenu.qml
qml/singletons/GlobalConfig.qml

it popped up testing the database gone watcher that the database was re-created
on every menu open. This is a bit too much persitence...

LoggerMenu: set last db/session once only (persistence hack)

---

qml/controls/logger/LoggerSettings.qml

Customer data is stored into a session when it is created. So there is no
reason to deny changes while recording is running.

LoggerSettings: Allow managing customer data while recording

---

qml/controls/logger/LoggerExport.qml

p_filter is equal "Snapshot". We will ignore Recordings here.
Exporting Recodings can take minutes and is not justifiable.
The customer can still export the complete database to get the Recordings.

Added tranaction filter to MtVis export call.

---

qml/controls/settings/ApplicationSettings.qml

* View persistency is so cool so why disable it?
* The text of the checkbox was so misleading that it confused everybody
So As long as nobody comes up with
* good argument why disable persistency is necessary
* a good text for the checkbox
remove it.

ApplicationSettings: Remove checkbox for view persistency

---

qml/Main.qml

With latest changes in zera-classes and modulemanager ref-session contains a
sec-entity which cannot be used by our measurement views.

Ensure not to display measurement views in ref-session

---

qml/controls/logger/LoggerExport.qml

main.xml is properly created for emptay session

LoggerExport: Show session empty warning only on result.xml

---

qml/controls/WaitTransaction.qml

The assumption that Popup.open() sets Popup.opened immediately is incorrect. So
aborting further activities in stopWait if popup is not open leads to a wait
forever.
Intention of this check was to avoid effects in case stopWait is called without
calling startWait before. Even if this happens: There is not damage to expect
so skip this test.

WaitTransaction: Ensure fast errors/warnings are displayed

---

qml/Main.qml
qml/controls/PageView.qml

| QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
* Tested on Qt5.14 target machin
* They are right it reads much better and syntax highlight works
* VERY INTERESTING: The is no signal stateChanged. How could this ever work??

 Fix connection syntax warnings on Qt5.15

---

qml/Main.qml
qml/controls/PageView.qml
src/main.cpp

Fixes initial crash on fresh development environment.
Signed-off-by: Anuja Mutalik <a.mutalik@zera.de>

Load "settings.json" from correct source path

---

.github/workflows/buildAndTest.yml
app/qml/singletons/FunctionTools.qml

We introduced auto scaling - or at places we still see decimal group separators we have to introduce auto scaling.

FunctionTools.qml: Remove removeDecimalGroupSeparators function

---

app/qml/controls/error_comparison_params/ParamViewComparison.qml

When language is German, text 'Zählerkonstante' and buttons overlap

ParamViewComparison: Adjust width of popButton and autoDutButton

---

app/qml/controls/ranges/RangeLine.qml

There are issues:
ATTOW vf-qmllib has this x/y thingy on vu nominal indicators. Go fix them and consider shapes suggested as target to support.

RangeLine.qml: Get more cooler on pixels

---

app/qml/controls/settings/SensorSettings.qml

* Currently, 'formatNumber' from FunctionTools is used
* Digits after decimal points are same as global config

SensorSettings: Format displayed parameters

---

app/qml/pages/EMOBActualValuesPageDC.qml

Do not specify left, right, and horizontalCenter anchors at the same time

EMOBActualValuesPageDC: remove QML warning

---

app/qml/controls/settings/SensorSettings.qml

If at least one Value is not NaN, we say a Ble sensor is found Otherwise, no sensor is found

SensorSettings: change decision on giving sensor's connectivity feedback

---

lib/lib-gui/qmlfileio.cpp

We saw logs missing helpful history

QmlFileIO::storeJournalctlOnUsb: Store logs since last boot

---

.github/workflows/triggerMetaUpdates.yml

* Do not wait for the triggered workflow to finish. Because, this check is asynchronous and sometimes causes a racing condition, meaning, it checks if the triggered workflow is finished successfully even before it started.
* Do not propagate success/failure of triggered workflow to this current workflow. Since we don't wait for triggered workflow to finish, propagating it's status doesn't make sense.

workflows/generateScpiDocs.yml: Update trigger workflow handling

---

lib/lib-gui/qmlfileio.cpp

since this is a client/server architecture, the client sends the command to initiate the copy of logs and dumps to the server, and waits for the success response.  At the same time the client has a timeout of x seconds in which it expects the response, otherwise it will indicate via GUI the failure of the copying/moving of the desired files. 
When devices run for a long time over several days, or large core dumps are to be copied, the time needed to fulfill the task can exceed the timeout of 25seconds. In these cases, the GUI will communicate to the user, the copying process has failed, because no success response from the server within the timeout. The server in turn will finish the copying of the files in the background without the user knowing. 
To prevent this, the timeout is …

SaveLogAndDumps: increase timeout to prevent false negative
